name: Security Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * 1'  # Weekly Monday at noon

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security-analysis:
    name: Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript  # PowerShell analyzed as JS
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      
  powershell-security:
    name: PowerShell Security Check
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run PSScriptAnalyzer
      shell: powershell
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
        $results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error,Warning
        if ($results) {
          $results | Format-Table -AutoSize
          Write-Error "PSScriptAnalyzer found issues"
        } else {
          Write-Host "✅ No PSScriptAnalyzer issues found"
        }
        
    - name: Check for sensitive patterns
      shell: powershell  
      run: |
        Write-Host "🔍 Checking for sensitive patterns..."
        
        # Check for hardcoded secrets/keys
        $sensitivePatterns = @(
          'password\s*=\s*"[^"]*"',
          'apikey\s*=\s*"[^"]*"',
          'secret\s*=\s*"[^"]*"',
          'token\s*=\s*"[^"]*"'
        )
        
        $found = $false
        Get-ChildItem *.ps1 -Recurse | ForEach-Object {
          $content = Get-Content $_.FullName -Raw
          foreach ($pattern in $sensitivePatterns) {
            if ($content -match $pattern) {
              Write-Warning "Potential sensitive data in $($_.Name): $pattern"
              $found = $true
            }
          }
        }
        
        if (-not $found) {
          Write-Host "✅ No sensitive patterns found"
        }

  defender-compatibility:
    name: Defender Compatibility Check
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check for Defender triggers
      shell: powershell
      run: |
        Write-Host "🛡️ Checking for Windows Defender trigger patterns..."
        
        $triggerPatterns = @{
          'Invoke-WebRequest' = 'Network download trigger'
          'Start-Process.*-Verb RunAs' = 'Privilege escalation trigger'
          'Invoke-Expression' = 'Dynamic code execution trigger'
          'FromBase64String' = 'Base64 encoding trigger'
          'DownloadString' = 'Web download trigger'
        }
        
        $issues = @()
        Get-ChildItem *.ps1 -Recurse | ForEach-Object {
          $content = Get-Content $_.FullName -Raw
          foreach ($pattern in $triggerPatterns.Keys) {
            if ($content -match $pattern) {
              $issues += "⚠️  $($_.Name): $($triggerPatterns[$pattern]) - Pattern: $pattern"
            }
          }
        }
        
        if ($issues) {
          Write-Warning "Potential Defender triggers found:"
          $issues | ForEach-Object { Write-Warning $_ }
          Write-Host "`n💡 See DEFENDER-WHITELIST.md for mitigation strategies"
        } else {
          Write-Host "✅ No known Defender trigger patterns found"
        }
        
    - name: Validate anti-false-positive measures
      shell: powershell
      run: |
        Write-Host "🔍 Validating anti-false-positive measures..."
        
        $mainScript = "hellion_tool_main.ps1"
        if (Test-Path $mainScript) {
          $content = Get-Content $mainScript -Raw
          
          # Check for security declarations
          if ($content -match "LEGITIMATE_SOFTWARE|SECURITY_DECLARATION") {
            Write-Host "✅ Security declarations found in main script"
          } else {
            Write-Warning "❌ Security declarations missing in main script"
          }
          
          # Check for anti-heuristic comments
          if ($content -match "\.SYNOPSIS|\.DESCRIPTION") {
            Write-Host "✅ Documentation comments found"
          } else {
            Write-Warning "❌ Documentation comments missing"
          }
        }
        
        # Check for defender-safe alternatives
        $defenderSafeCount = 0
        Get-ChildItem *.ps1 -Recurse | ForEach-Object {
          $content = Get-Content $_.FullName -Raw
          if ($content -match "Defender-safe|ProcessStartInfo|Test-NetConnection") {
            $defenderSafeCount++
          }
        }
        
        Write-Host "✅ $defenderSafeCount files contain Defender-safe patterns"